from __future__ import annotations

from pathlib import Path
import shutil
import sys


# Keep the distributable source tree free of bytecode generated by pytest.
sys.dont_write_bytecode = True


def pytest_sessionstart(session) -> None:
    cache = Path(__file__).resolve().parent / "__pycache__"
    if cache.is_dir():
        shutil.rmtree(cache)